default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  host: localhost
  username: <%= ENV['DEV_USERNAME'] %>
  password: <%= ENV['DEV_PASSWORD'] %>

development:
  <<: *default
  database: finhelp_dev

test:
  <<: *default
  database: finhelp_test

production:
  <<: *default
  database: finhelp
  host: <%= ENV['PROD_HOST'] %>
  username: <%= ENV['PROD_USERNAME'] %>
  password: <%= ENV['PROD_USERNAME'] %>  