default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  host: <%= ENV['DEV_HOST'] %>
  username: <%= ENV['DEV_USERNAME'] %>
  password: <%= ENV['DEV_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DEV_DATABASE'] %>

test:
  <<: *default
  database: finhelp_test

production:
  <<: *default
  database: <%= ENV['PROD_DATABASE'] %>
  host: <%= ENV['PROD_HOST'] %>
  username: <%= ENV['PROD_USERNAME'] %>
  password: <%= ENV['PROD_USERNAME'] %>  