default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: finhelp_dev

test:
  <<: *default
  database: finhelp_test

production:
  <<: *default
  database: finhelp