# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Extracao.create([
	{
		agenciaug: 694,
		data: "26/02/2019",
		sequencialdata: 1,
		sequencial: 1,
		ug: 158327,
		operador: "39398189097",
		tipodh: "RP",
		dataemissao: "26/02/2019",
		datavencimento: "08/03/2019",
		observacao: "PAGAMENTO DE AUXÍLIO MORADIA PARA ALUNOS DO IFRS CAMPUS OSÓRIO, ASSISTÊNCIA ESTUDANTIL, MARÇO DE 2019, PROC. 23367.000043/2019-50.",
		processodh: "23367.000043/2019-50",
		dataateste: "26/02/2019",
		credor: "39398189097",
		datapagamento: "08/03/2019",
		dtemissaodocorigem: "26/02/2019",
		numerodocorigem: "MARÇO/19",
		situacao: "DSP061",
		empenho: "2019NE000004",
		valor: 168.00,
		contavpd: 394110100,
		centrodecusto: "CC-GENERICO",
		mes: 3,
		ano: 2019,
		codigosiorg: 105241,
		tipoob: "OBC",
		banco: "0",
		agencia: "0",
		contafavorecido: "0",
		contapagadora: "UNICA",
	}
])

Banco.create([
	{ codigo: "001",  nome: "Banco do Brasil S.A." },
	{ codigo: "341",  nome: "Banco Itaú S.A." },
	{ codigo: "033",  nome: "Banco Santander (Brasil) S.A." },
	{ codigo: "356",  nome: "Banco Real S.A. (antigo)" },
	{ codigo: "652",  nome: "Itaú Unibanco Holding S.A." },
	{ codigo: "237",  nome: "Banco Bradesco S.A." },
	{ codigo: "745",  nome: "Banco Citibank S.A." },
	{ codigo: "399",  nome: "HSBC Bank Brasil S.A. – Banco Múltiplo" },
	{ codigo: "104",  nome: "Caixa Econômica Federal" },
	{ codigo: "389",  nome: "Banco Mercantil do Brasil S.A." },
	{ codigo: "453",  nome: "Banco Rural S.A." },
	{ codigo: "422",  nome: "Banco Safra S.A." },
	{ codigo: "633",  nome: "Banco Rendimento S.A." },
	{ codigo: "246",  nome: "Banco ABC Brasil S.A." },
	{ codigo: "025",  nome: "Banco Alfa S.A." },
	{ codigo: "641",  nome: "Banco Alvorada S.A." },
	{ codigo: "029",  nome: "Banco Banerj S.A." },
	{ codigo: "038",  nome: "Banco Banestado S.A." },
	{ codigo: "000",  nome: "Banco Bankpar S.A." },
	{ codigo: "740",  nome: "Banco Barclays S.A." },
	{ codigo: "107",  nome: "Banco BBM S.A." },
	{ codigo: "031",  nome: "Banco Beg S.A." },
	{ codigo: "096",  nome: "Banco BM&F de Serviços de Liquidação e Custódia S.A" },
	{ codigo: "318",  nome: "Banco BMG S.A." },
	{ codigo: "752",  nome: "Banco BNP Paribas Brasil S.A." },
	{ codigo: "248",  nome: "Banco Boavista Interatlântico S.A." },
	{ codigo: "036",  nome: "Banco Bradesco BBI S.A." },
	{ codigo: "204",  nome: "Banco Bradesco Cartões S.A." },
	{ codigo: "225",  nome: "Banco Brascan S.A." },
	{ codigo: "044",  nome: "Banco BVA S.A." },
	{ codigo: "263",  nome: "Banco Cacique S.A." },
	{ codigo: "473",  nome: "Banco Caixa Geral – Brasil S.A." },
	{ codigo: "222",  nome: "Banco Calyon Brasil S.A." },
	{ codigo: "040",  nome: "Banco Cargill S.A." },
	{ codigo: "M08",  nome: "Banco Citicard S.A." },
	{ codigo: "M19",  nome: "Banco CNH Capital S.A." },
	{ codigo: "215",  nome: "Banco Comercial e de Investimento Sudameris S.A." },
	{ codigo: "756",  nome: "Banco Cooperativo do Brasil S.A. – BANCOOB" },
	{ codigo: "748",  nome: "Banco Cooperativo Sicredi S.A." },
	{ codigo: "505",  nome: "Banco Credit Suisse (Brasil) S.A." },
	{ codigo: "229",  nome: "Banco Cruzeiro do Sul S.A." },
	{ codigo: "003",  nome: "Banco da Amazônia S.A." },
	{ codigo: "0833", nome: "Banco da China Brasil S.A." },
	{ codigo: "707",  nome: "Banco Daycoval S.A." },
	{ codigo: "M06",  nome: "Banco de Lage Landen Brasil S.A." },
	{ codigo: "024",  nome: "Banco de Pernambuco S.A. – BANDEPE" },
	{ codigo: "456",  nome: "Banco de Tokyo-Mitsubishi UFJ Brasil S.A." },
	{ codigo: "214",  nome: "Banco Dibens S.A." },
	{ codigo: "047",  nome: "Banco do Estado de Sergipe S.A." },
	{ codigo: "037",  nome: "Banco do Estado do Pará S.A." },
	{ codigo: "041",  nome: "Banco do Estado do Rio Grande do Sul S.A." },
	{ codigo: "004",  nome: "Banco do Nordeste do Brasil S.A." },
	{ codigo: "265",  nome: "Banco Fator S.A." },
	{ codigo: "M03",  nome: "Banco Fiat S.A." },
	{ codigo: "224",  nome: "Banco Fibra S.A." },
	{ codigo: "626",  nome: "Banco Ficsa S.A." },
	{ codigo: "394",  nome: "Banco Finasa BMC S.A." },
	{ codigo: "M18",  nome: "Banco Ford S.A." },
	{ codigo: "233",  nome: "Banco GE Capital S.A." },
	{ codigo: "734",  nome: "Banco Gerdau S.A." },
	{ codigo: "M07",  nome: "Banco GMAC S.A." },
	{ codigo: "612",  nome: "Banco Guanabara S.A." },
	{ codigo: "M22",  nome: "Banco Honda S.A." },
	{ codigo: "063",  nome: "Banco Ibi S.A. Banco Múltiplo" },
	{ codigo: "M11",  nome: "Banco IBM S.A." },
	{ codigo: "604",  nome: "Banco Industrial do Brasil S.A." },
	{ codigo: "320",  nome: "Banco Industrial e Comercial S.A." },
	{ codigo: "653",  nome: "Banco Indusval S.A." },
	{ codigo: "630",  nome: "Banco Intercap S.A." },
	{ codigo: "249",  nome: "Banco Investcred Unibanco S.A." },
	{ codigo: "184",  nome: "Banco Itaú BBA S.A." },
	{ codigo: "479",  nome: "Banco ItaúBank S.A" },
	{ codigo: "M09",  nome: "Banco Itaucred Financiamentos S.A." },
	{ codigo: "376",  nome: "Banco J. P. Morgan S.A." },
	{ codigo: "074",  nome: "Banco J. Safra S.A." },
	{ codigo: "217",  nome: "Banco John Deere S.A." },
	{ codigo: "065",  nome: "Banco Lemon S.A." },
	{ codigo: "600",  nome: "Banco Luso Brasileiro S.A." },
	{ codigo: "755",  nome: "Banco Merrill Lynch de Investimentos S.A." },
	{ codigo: "746",  nome: "Banco Modal S.A." },
	{ codigo: "151",  nome: "Banco Nossa Caixa S.A." },
	{ codigo: "045",  nome: "Banco Opportunity S.A." },
	{ codigo: "623",  nome: "Banco Panamericano S.A." },
	{ codigo: "611",  nome: "Banco Paulista S.A." },
	{ codigo: "643",  nome: "Banco Pine S.A." },
	{ codigo: "638",  nome: "Banco Prosper S.A." },
	{ codigo: "747",  nome: "Banco Rabobank International Brasil S.A." },
	{ codigo: "M16",  nome: "Banco Rodobens S.A." },
	{ codigo: "072",  nome: "Banco Rural Mais S.A." },
	{ codigo: "250",  nome: "Banco Schahin S.A." },
	{ codigo: "749",  nome: "Banco Simples S.A." },
	{ codigo: "366",  nome: "Banco Société Générale Brasil S.A." },
	{ codigo: "637",  nome: "Banco Sofisa S.A." },
	{ codigo: "464",  nome: "Banco Sumitomo Mitsui Brasileiro S.A." },
	{ codigo: "0825", nome: "Banco Topázio S.A." },
	{ codigo: "M20",  nome: "Banco Toyota do Brasil S.A." },
	{ codigo: "634",  nome: "Banco Triângulo S.A." },
	{ codigo: "208",  nome: "Banco UBS Pactual S.A." },
	{ codigo: "M14",  nome: "Banco Volkswagen S.A." },
	{ codigo: "655",  nome: "Banco Votorantim S.A." },
	{ codigo: "610",  nome: "Banco VR S.A." },
	{ codigo: "370",  nome: "Banco WestLB do Brasil S.A." },
	{ codigo: "021",  nome: "BANESTES S.A. Banco do Estado do Espírito Santo" },
	{ codigo: "719",  nome: "Banif-Banco Internacional do Funchal (Brasil) S.A." },
	{ codigo: "073",  nome: "BB Banco Popular do Brasil S.A." },
	{ codigo: "078",  nome: "BES Investimento do Brasil S.A.-Banco de Investimento" },
	{ codigo: "069",  nome: "BPN Brasil Banco Múltiplo S.A." },
	{ codigo: "070",  nome: "BRB - Banco de Brasília S.A." },
	{ codigo: "477",  nome: "Citibank N.A." },
	{ codigo: "0817", nome: "Concórdia Banco S.A." },
	{ codigo: "487",  nome: "Deutsche Bank S.A. – Banco Alemão" },
	{ codigo: "751",  nome: "Dresdner Bank Brasil S.A. – Banco Múltiplo" },
	{ codigo: "062",  nome: "Hipercard Banco Múltiplo S.A." },
	{ codigo: "492",  nome: "ING Bank N.V." },
	{ codigo: "488",  nome: "JPMorgan Chase Bank" },
	{ codigo: "409",  nome: "UNIBANCO – União de Bancos Brasileiros S.A." },
	{ codigo: "230",  nome: "Unicard Banco Múltiplo S.A." }
])